## Copyright (C) Brodie Gaslam
##
## This file is part of "r2c - Fast Iterated Statistic Computation in R"
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 2 or 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## Go to <https://www.r-project.org/Licenses> for copies of the licenses.

# - Copy Prior Result for No-ops -----------------------------------------------

# No-op functions like assignment and braces don't compute, thus don't write to
# memory.  To ensure that their "output" is written to the result vector, we
# need to make sure it is explicitly copied (e.g. when we assign an external
# symbol, we actually want that copied into the result).

f_copy <- '
// Copy a vector, intended to be copied to result
static void %s(%s) {
  R_xlen_t len0 = lens[di[0]];
  double * res = data[di[1]];
  double * input = data[di[0]];
  // this should be a debug mode check only
  if(res == input) Rf_error("Internal Error: copying in-place.");
  memcpy(res, input, sizeof(*res) * len0);
  lens[di[1]] = len0;
}'

code_gen_copy <- function(fun, pars, par.types) {
  vetr(
    identical(., "vcopy"),
    pars=list(NULL),
    par.types=character() && all(. %in% PAR.INT)
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_copy, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name)
}
#' Copy a Vector Into a New One
#'
#' Copies a vector into a new memory location.  This function is intended solely
#' for documentation purposes of calls generated by `r2c` as part of the
#' compilation process.  In some cases, it is necessary for `r2c` to explicitly
#' copy a variable into the result vector.  This is achieved by the C
#' counterpart of this function.  Since all other `r2c` C functions have R
#' counterparts, we add this R counterpart for consistency.  Unlike all the
#' other `r2c` supported function, this one is never looked up on the search
#' path so even if it is masked there will not be an error.  There is no reason
#' to ever use this function directly.
#'
#' @param x numeric vector to copy
#' @return `x`, copied to a new location
#' @export

vcopy <- function(x) x + 0

# No-op functions like assignment and braces don't compute, thus don't write to
# memory.  To ensure that their "output" is written to the result vector, we
# need to make sure it is explicitly copied (e.g. when we assign an external
# symbol, we actually want that copied into the result).

f_rec <- '
// Reconciliation is a no-op
// static void %s(%s) { /* NOOP */ }'

code_gen_rec <- function(fun, pars, par.types) {
  vetr(
    identical(., "rec"),
    pars=list(NULL),
    par.types=character() && all(. %in% PAR.INT)
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_rec, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name, out.ctrl=CGEN.OUT.NONE)
}
#' Mark a Vector for Reconciliation
#'
#' "Internal" function that `r2c` uses for book-keeping of what expressions need
#' to be reconciled across branches so that post-branch expressions can address
#' their side effects (i.e. assignments) or results irrespective of what branch
#' was taken at run time.  This function is exposed only so that users can
#' understand what it is should they see it in processed `r2c` calls.
#'
#' @param x numeric vector to reconcile.
#' @return `x`
#' @export

rec <- function(x) x

# - Braces and Assign ----------------------------------------------------------

f_braces <- '
// Braces are a no-op; allocation handles them.
// static void %s(%s) { /* NOOP */ }'
code_gen_braces <- function(fun, pars, par.types) {
  vetr(
    identical(., "{"),
    pars=list(),
    par.types=character() && all(. %in% PAR.INT)
  )
  if(length(pars) < 1L) stop("Empty braces expresssions disallowed.")
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_braces, name, toString(c(F.ARGS.BASE, F.ARGS.VAR)))
  code_res(defn=defn, narg=TRUE, name=name, out.ctrl=CGEN.OUT.NONE)
}

f_assign <- '
// Read-only assignments are a no-op; allocation handles them.
// static void %s(%s) { /* NOOP */ }'
code_gen_assign <- function(fun, pars, par.types) {
  vetr(
    isTRUE(. %in% c("=", "<-")),
    pars=list(NULL, NULL),
    par.types=character() && all(. %in% PAR.INT)
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_assign, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name, out.ctrl=CGEN.OUT.NOOP)
}
# Transform for Complex Assignments
#
# E.g. turn things like `x[s] <- y` into `subassign(x, s, y)`.
#
# See code-subset.R

assign_transform <- function(call) {
  if(!is.call(call))
    stop("Internal Error: expected call but got ", typeof(call))
  if(length(call) != 3L)
    stop(
      "Internal Error: expected length 3 assign call but got:\n",
      deparseLines(call)
    )

  call.sym <- get_lang_name(call)
  if(call.sym %in% ASSIGN.SYM.BASE) {
    if(is.call(call[[2L]]) && get_lang_name(call[[2L]]) == "[") {
      if(length(call[[2L]]) == 3L && is.symbol(call[[c(2L,2L)]])) {
        call <- call("x", call[[c(2L,2L)]], call[[c(2L,3L)]], call[[3L]])
        call[[1L]] <- call("::", quote(r2c), quote(subassign))
        names(call) <- c('', 'x', 's', 'y')
      } else {
        stop("Unsupported sub-assignment form:\n", deparseLines(call))
      }
    }
  }
  call
}

