## Copyright (C) Brodie Gaslam
##
## This file is part of "r2c - Fast Iterated Statistic Computation in R"
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 2 or 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## Go to <https://www.r-project.org/Licenses> for copies of the licenses.

f_braces <- '
// Braces are a no-op; allocation handles them.
// static void %s(%s) { /* NOOP */ }'

code_gen_braces <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "{"),
    args.reg=list(),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  if(length(args.reg) < 1L) stop("Empty braces expresssions disallowed.")
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_braces, name, toString(c(F.ARGS.BASE, F.ARGS.VAR)))
  code_res(defn=defn, narg=TRUE, name=name, noop=TRUE)
}

f_assign <- '
// Read-only assignments are a no-op; allocation handles them.
// static void %s(%s) { /* NOOP */ }'
code_gen_assign <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    isTRUE(. %in% c("=", "<-")),
    args.reg=list(NULL, NULL),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_assign, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name, noop=TRUE)
}

f_copy <- '
// Copy a vector, intended to be copied to result
static void %s(%s) {
  R_xlen_t len0 = lens[di[0]];
  double * res = data[di[1]];
  double * input = data[di[0]];
  // this should be a debug mode check only
  if(res == input) Rf_error("Internal Error: copying in-place.");
  memcpy(res, input, sizeof(*res) * len0);
  lens[1] = len0;
}'
# This function will get run, but the results discarded.  We started off using
# it, but decided later easier to skip braces altogether, and it was easier to
# leave this vestigial code here.

code_gen_copy <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "vcopy"),
    args.reg=list(),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_copy, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name)
}
#' Copy a Vector Into a New One
#'
#' Copies a vector into a new memory location.  This function is intended solely
#' for documentation purposes of calls generated by `r2c` as part of the
#' compilation process.  In some cases, it is necessary for `r2c` to explicitly
#' copy a variable into the result vector.  This is achieved by the C
#' counterpart of this function.  Since all other `r2c` C functions have R
#' counterparts, we add this R counterpart for consistency.  Unlike all the
#' other `r2c` supported function, this one is never looked up on the search
#' path so even if it is masked there will not be an error.  There is no reason
#' to ever use this function directly.
#'
#' @param x numeric vector to copy
#' @return `x`, copied to a new location
#' @export

vcopy <- function(x) x + 0
