## Copyright (C) Brodie Gaslam
##
## This file is part of "r2c - Fast Iterated Statistic Computation in R"
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 2 or 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## Go to <https://www.r-project.org/Licenses> for copies of the licenses.

# - Copy Prior Result for No-ops -----------------------------------------------

# No-op functions like assignment and braces don't compute, thus don't write to
# memory.  To ensure that their "output" is written to the result vector, we
# need to make sure it is explicitly copied (e.g. when we assign an external
# symbol, we actually want that copied into the result).

f_copy <- '
// Copy a vector, intended to be copied to result
static void %s(%s) {
  R_xlen_t len0 = lens[di[0]];
  double * res = data[di[1]];
  double * input = data[di[0]];
  // this should be a debug mode check only
  if(res == input) Rf_error("Internal Error: copying in-place.");
  memcpy(res, input, sizeof(*res) * len0);
  lens[1] = len0;
}'

code_gen_copy <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "vcopy"),
    args.reg=list(),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_copy, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name)
}
#' Copy a Vector Into a New One
#'
#' Copies a vector into a new memory location.  This function is intended solely
#' for documentation purposes of calls generated by `r2c` as part of the
#' compilation process.  In some cases, it is necessary for `r2c` to explicitly
#' copy a variable into the result vector.  This is achieved by the C
#' counterpart of this function.  Since all other `r2c` C functions have R
#' counterparts, we add this R counterpart for consistency.  Unlike all the
#' other `r2c` supported function, this one is never looked up on the search
#' path so even if it is masked there will not be an error.  There is no reason
#' to ever use this function directly.
#'
#' @param x numeric vector to copy
#' @return `x`, copied to a new location
#' @export

vcopy <- function(x) x + 0

# - Braces and Assign ----------------------------------------------------------

f_braces <- '
// Braces are a no-op; allocation handles them.
// static void %s(%s) { /* NOOP */ }'
code_gen_braces <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "{"),
    args.reg=list(),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  if(length(args.reg) < 1L) stop("Empty braces expresssions disallowed.")
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_braces, name, toString(c(F.ARGS.BASE, F.ARGS.VAR)))
  code_res(defn=defn, narg=TRUE, name=name, out.ctrl=CGEN.OUT.NONE)
}

f_assign <- '
// Read-only assignments are a no-op; allocation handles them.
// static void %s(%s) { /* NOOP */ }'
code_gen_assign <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    isTRUE(. %in% c("=", "<-")),
    args.reg=list(NULL, NULL),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_assign, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name, out.ctrl=CGEN.OUT.NOOP)
}
# - If / Else ------------------------------------------------------------------

f_iftest <- '
// Check a test condition, mostly enforces length
static int %s(%s) {
  if(lens[di[0]] != 1) {
    if(lens[di[0]] > 1) Rf_error("the condition has length > 1");
    else if(lens[di[0]] < 1) Rf_error("the condition is of length zero");
  }
  lens[di[1]] = 1;
  return (int) data[di[0]][0];
}'

f_ifother <- '
// if/else does not generate a definition
// static void %s(%s) { /* NOOP */ }'

code_gen_if_test <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "if_test"),
    args.reg=list(NULL),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_iftest, name, toString(F.ARGS.BASE))
  code_res(
    defn=defn, name=name,
    c.call.gen=function(...)
      paste0("if(", sub(";$", "", c_call_gen(...)), ") {")
  )
}
code_gen_if_true <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "if_true"),
    args.reg=list(NULL),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_ifother, name, toString(F.ARGS.BASE))
  code_res(
    defn=defn, name=name, c.call.gen=function(...) "} else {",
    out.ctrl=CGEN.OUT.CALL
  )
}
code_gen_if_false <- function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "if_false"),
    args.reg=list(NULL),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_ifother, name, toString(F.ARGS.BASE))
  code_res(
    defn=defn, name=name, c.call.gen=function(...) "}", out.ctrl=CGEN.OUT.CALL
  )
}
code_gen_r2c_if <-function(fun, args.reg, args.ctrl, args.flags) {
  vetr(
    identical(., "r2c_if"),
    args.reg=list(NULL, NULL),
    args.ctrl=list() && length(.) == 0L,
    args.flags=list() && length(.) == 0L
  )
  name <- FUN.NAMES[fun]
  defn <- sprintf(f_ifother, name, toString(F.ARGS.BASE))
  code_res(defn=defn, name=name, out.ctrl=CGEN.OUT.NONE)
}
code_gen_if <- function(...) {
  stop(
    "Internal Error: attempting to generate code for raw `if/else` ",
    "instead of decomponsed one."
  )
}
#' Decompose If / Else
#'
#' Internal functions that integrate the `if / else` construct between the R and
#' C level.  These are purely an implementation detail and not intended to be
#' used directly, but are documented so users can understand what they are if
#' they encounter them when inspect "r2c_fun" objects.
#'
#' Most R level calls are converted 1-1 into a C level call.  Control structures
#' are more complicated because we need to generate the call structure itself
#' without a direct correspondence of R call to structural element.  This
#' decomposition creates that correspondence without changing the overall
#' semantics (although the intermediate semantics are not the same due to the
#' use of implicit state to decide what branch to evaluate).  Unlike most other
#' `r2c` functions, you cannot run these from the R level at all.  There is only
#' a loose correspondence between the R function names and the C code they cause
#' to be generated as we exploit how `r2c` linearizes the AST to cause the
#' pieces of the control structure to be emitted at the right spots.
#'
#' Put less kindly: this is a hack to get control flow to fit into an
#' implementation that originally did not intend to allow them.
#'
#' @param true expression to evaluate if previous `if_test` is TRUE.
#' @param false expression to evaluate if previous `if_test` is FALSE
#' @param expr an expression to evaluate
#' @return for `if_true` and `if_false`, the result of evaluating `expr`, for
#'   `if_test` the result of evaluating `test` if that is length 1 (otherwise an
#'   error) 
#' @examples
#' get_r_code(r2cq(if(a) b else c), raw=TRUE)

r2c_if <- function(true, false)
  stop("This is an internal `r2c` function unavailable for direct use.")

#' @rdname r2c_if
if_true <- function(expr)
  stop("This is an internal `r2c` function unavailable for direct use.")

#' @rdname r2c_if
if_false <- function(expr)
  stop("This is an internal `r2c` function unavailable for direct use.")

#' @rdname r2c_if
if_test <- function(cond)
  stop("This is an internal `r2c` function unavailable for direct use.")
